### ISSUE TITLE
Plugin Permissions - Making plugin avaible only for admins

### ISSUE THREAD

**Issue by nesquik21** [Franc1sco/Franug-Knifes#1]
Hi Franc1sco,
I have a CS:GO ds and I want to make this plugin avaible to use only for admins, as your last !ws plugin does. Can you help me please?
When I realized that !ws could be accesed only by admins and !knife by all, i've started to search for permissions, anything in plugin files, but I've didn't found anything that could help me. Also I've search on the internet how to deny commands for other players that aren't admins, but nothing as well.
If you can help me do this in any mode, i will be thankful.
Thanks in advance, have a nice day.

**Comment by iGreen123** [comment]
use admin overides

if you use sourcebans then

"SB_Overrides"
{
    "override_commands"
    {
        "sm_knife"  "a"
    }
}

if you dont use sourcebans then

Overrides
{
"sm_knife"  "a" 
}

i guess that should work
