### ISSUE TITLE
ZR Issues

### ISSUE THREAD

**Issue by cTmoNe** [Franc1sco/Franug-Knifes#12]
L 07/01/2016 - 14:27:33: [SM] Call stack trace:
L 07/01/2016 - 14:27:33: [SM]   [0] SetEntProp
L 07/01/2016 - 14:27:33: [SM]   [1] Line 956, E:\GitHub\Franug-Weapon_Paints\franug_weaponpaints_private.sp::ChangePaint()
L 07/01/2016 - 14:27:33: [SM]   [2] Line 1020, E:\GitHub\Franug-Weapon_Paints\franug_weaponpaints_private.sp::OnPostWeaponEquip()
L 07/01/2016 - 14:27:33: [SM]   [4] CS_RespawnPlayer
L 07/01/2016 - 14:27:33: [SM]   [5] Line 185, zr/respawn.inc::RespawnSpawnClient()
L 07/01/2016 - 14:27:33: [SM]   [6] Line 266, zr/zspawn.inc::ZSpawnClient()
L 07/01/2016 - 14:27:33: [SM]   [7] Line 349, zr/zspawn.inc::ZSpawnCommand()
L 07/01/2016 - 14:27:33: [SM] Exception reported: Cannot set m_iItemDefinitionIndex with "FollowCSGOServerGuidelines" option enabled.
L 07/01/2016 - 14:27:33: [SM] Blaming: sm_franugknife.smx()
L 07/01/2016 - 14:27:33: [SM] Call stack trace:
L 07/01/2016 - 14:27:33: [SM]   [0] SetEntProp
L 07/01/2016 - 14:27:33: [SM]   [1] Line 50, E:\Gi Exception reported: Cannot set m_iItemDefinitionIndex with "FollowCSGOServerGuidelines" option enabled.
L 07/01/2016 - 14:27:33: [SM] Blaming: sm_franugknife.smx()
L 07/01/2016 - 14:27:33: [SM] Call stack trace:
L 07/01/2016 - 14:27:33: [SM]   [0] SetEntProp
L 07/01/2016 - 14:27:33: [SM]   [1] Line 50, E:\GitHub\Franug-Knifes\sm_franugknife.sp::OnPostWeaponEquip()
L 07/01/2016 - 14:27:33: [SM]   [3] GivePlayerItem
L 07/01/2016 - 14:27:33: [SM]   [4] Line 860, zr/weapons/weapons.inc::WeaponsRefreshClientWeapon()
L 07/01/2016 - 14:27:33: [SM]   [5] Line 937, zr/weapons/weapons.inc::WeaponsRefreshAllClientWeapons()
L 07/01/2016 - 14:27:33: [SM]   [6] Line 366, zr/weapons/weapons.inc::WeaponsOnClientSpawnPost()
L 07/01/2016 - 14:27:33: [SM]   [7] Line 218, zr/event.inc::EventtHub\Franug-Knifes\sm_franugknife.sp::OnPostWeaponEquip()
L 07/01/2016 - 14:27:33: [SM]   [3] GivePlayerItem
L 07/01/2016 - 14:27:33: [SM]   [4] Line 911, zr/weapons/weapons.inc::WeaponsRemoveAllClientWeapons()
L 07/01/2016 - 14:27:33: [SM]   [5] Line 815, zr/infect.inc::InfectHumanToZombie()
L 07/01/2016 - 14:27:33: [SM]   [6] Line 193, zr/respawn.inc::RespawnSpawnClient()
L 07/01/2016 - 14:27:33: [SM]   [7] Line 266, zr/zspawn.inc::ZSpawnClient()
L 07/01/2016 - 14:27:33: [SM]   [8] Line 349, zr/zspawn.inc::ZSpawnCommand()
L 07/01/2016 - 14:27:33: [SM]PlayerSpawnPost()

**Comment by Franc1sco** [comment]
addons/sourcemod/configs/core.cfg  `"FollowCSGOServerGuidelines" "no"` And solved.

**Comment by cTmoNe** [comment]
Ok
