### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by oaaron99** [Franc1sco/Franug-Knifes#15]
> Failed to set custom material for 'knife_flip', no matching material name found on model models/weapons/w_knife_default_t.mdl
> Failed to set custom material for 'karam', no matching material name found on model models/weapons/w_knife_default_ct.mdl
> Failed to set custom material for 'knife_survival_bowie', no matching material name found on model models/weapons/w_knife_default_ct.mdl
> Failed to set custom material for 'knife_butterfly', no matching material name found on model models/weapons/w_knife_default_ct.mdl
> Failed to set custom material for 'knife_flip', no matching material name found on model models/weapons/w_knife_default_t.mdl
> Failed to set custom material for 'knife_survival_bowie', no matching material name found on model models/weapons/w_knife_default_ct.mdl
> Failed to set custom material for 'karam', no matching material name found on model models/weapons/w_knife_default_ct.mdl
> Failed to set custom material for 'karam', no matching material name found on model models/weapons/w_knife_default_ct.mdl
> Failed to set custom material for 'knife_flip', no matching material name found on model models/weapons/w_knife_default_t.mdl

Errors like that are spammed in game console rapidly for clients

**Comment by Weeeishy** [comment]
Yeah, it's kinda annoying, wish there is a way to suppress it.

**Comment by rogeraabbccdd** [comment]
You can try my knife plugin, it's totally free.
https://github.com/rogeraabbccdd/Knife-Upgrade/

**Comment by oaaron99** [comment]
lol deleting comments?

**Comment by Franc1sco** [comment]
Get support in the private versions
