### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by gergesh** [Franc1sco/Franug-Knifes#3]
I've placed the 2 files into the appropriate folders, when I type !knife the menu shows up but none of the knives load upon selection. I'll just stay with the default knife. If I have a zeus equipped there will be no knife at all.

**Comment by gergesh** [comment]
Solved by changing "FollowCSGOServerGuidelines" to no. You should probably add that to the readme both here and in the !ws plugin to save noobs (aka me) some time.

**Comment by moderatorman** [comment]
I've tried this method and it still doesn't work, do I have to have something in the command line arguments?

**EDIT:** I fixed the issue by changing the map.
