### ISSUE TITLE
Plugin problem

### ISSUE THREAD

**Issue by demoni123** [Franc1sco/Franug-Knifes#5]
Hi,
I want to ask for some help , im new in plugin world ,so the answer might be obvious , but I still want to ask you for some advice . I have a hosted serwer and I have tried to install ur knife plugin but the problem is  , when I've done everything like in ur tutorial , when i go to game and type !knife I can pick one of the knives but I cant see them , and Im just without any knife in my hand . 
I Hope u can help me ;)

**Comment by SirBarclay** [comment]
go into your "addons/sourcemod/config.cfg" file and at the bottom set 

"FollowCSGOServerGuidelines"	"no"

**Comment by Weeeishy** [comment]
@SirBarclay you mean core.cfg right?

**Comment by SirBarclay** [comment]
Yes, I kept muddling myself up.

**Comment by demoni123** [comment]
Thanks :)
